version: "3"
services:

  postgres:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=museo-db
    ports:
      - "5432:5432"
    volumes:
      - PGDATA:/var/lib/postgresql/data


  api:
    depends_on:
      - postgres
    container_name: api
    build: ./dvdb-api
    restart: always
    ports:
      - "4000:4000"

  website:
    depends_on:
      - api
    container_name: website
    build: ./website-ts
    restart: always
    ports:
      - "80:3000"


volumes:
  PGDATA:
  PGDATA-TEST:



    
