/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";


type Props = {
  path: string;
  position: any
};

const Persian = ({ path, position }: Props) => {
  const { scene } = useGLTF(path, true);
  return (
    <primitive position={position} object={scene} dispose={null} />
  );
};



export default Persian;
