/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const Persian = ({ ...props }) => {
  const { scene } = useGLTF("/data/models/Persian.glb", true);
  return (
    <primitive position={[0, -0.15, 0]} object={scene} dispose={null} />
  );
};



export default Persian;
